image: Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
  - cmd: nuget install NUnit.Console -Version 3.12.0 -OutputDirectory tools
  - cmd: nuget install OpenCover -Version 4.7.922 -OutputDirectory tools
  - cmd: nuget restore
  - cmd: choco install codecov
build:
  project: ReqIFSharp.sln
test:
  assemblies:  
    - '**\*.tests.dll'